eureka:
  client:
    healthcheck:
      enabled: true
    eureka-connection-idle-timeout-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://${DISCOVERY_SECURITY_USER_NAME}:${DISCOVERY_SECURITY_USER_PASSWORD}@${DISCOVERY_HOST_01}:${DISCOVERY_PORT}/eureka/,http://${DISCOVERY_SECURITY_USER_NAME}:${DISCOVERY_SECURITY_USER_PASSWORD}@${DISCOVERY_HOST_02}:${DISCOVERY_PORT}/eureka/
  instance:
    app-name: '@artifactId@'
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui/
    health-check-url-path: /actuator/health

xcan:
  trace:
    enabled: false
  cloud:
    gmApiUrlPrefix: ${GM_CLOUD_APIS_URL_PREFIX}
  mockService:
    domainSuffix: ${MOCK_SERVICE_DOMAIN_SUFFIX}
    testerApisUrlPrefix: ${MOCK_SERVICE_TESTER_APIS_URL_PREFIX}
  datasource:
    extra:
      dbType: '@databaseType@'
      dbMode: '@databaseMode@'
      entityPackages:
        - cloud.xcan.angus.idgen.entity
        - cloud.xcan.angus.api.commonlink
        - cloud.xcan.angus.core.tester.domain
    hikari:
      readOnly: false
      connectionTestQuery: SELECT 1 FROM DUAL
      poolName: xcanHikariCP
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 30
      minimumIdle: 10
    mysql:
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://${TESTER_MYSQL_HOST}:${TESTER_MYSQL_PORT}/${TESTER_MYSQL_DB}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=${info.app.timezone}&rewriteBatchedStatements=true
      username: ${TESTER_MYSQL_USER}
      password: ${TESTER_MYSQL_PASSWORD}
      schema:
        - mysql/idgen-schema.sql
    postgresql:
      driverClassName: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:postgresql://${TESTER_POSTGRES_HOST}:${TESTER_POSTGRES_PORT}/${TESTER_POSTGRES_DB}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=${info.app.timezone}&rewriteBatchedStatements=true
      username: ${TESTER_POSTGRES_USER}
      password: ${TESTER_POSTGRES_PASSWORD}
      schema:
        - postgres/idgen-schema.sql
    commonlink:
      mysql:
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://${COMMON_MYSQL_HOST}:${COMMON_MYSQL_PORT}/${COMMON_MYSQL_DB}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=${info.app.timezone}&rewriteBatchedStatements=true
        username: ${COMMON_MYSQL_USER}
        password: ${COMMON_MYSQL_PASSWORD}
      postgresql:
        driverClassName: org.postgresql.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://${COMMON_POSTGRES_HOST}:${COMMON_POSTGRES_PORT}/${COMMON_POSTGRES_DB}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=${info.app.timezone}&rewriteBatchedStatements=true
        username: ${COMMON_POSTGRES_USER}
        password: ${COMMON_POSTGRES_PASSWORD}
  redis:
    enabled: true
    deployment: ${TESTER_REDIS_DEPLOY_MODE:SINGLE}
    host: ${TESTER_REDIS_HOST}
    port: ${TESTER_REDIS_PORT}
    password: ${TESTER_REDIS_PASSWORD}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 5

spring:
  security:
    oauth2:
      resource-server:
        opaque-token:
          client-id: ${OAUTH2_INTROSPECT_CLIENT_ID}
          client-secret: ${OAUTH2_INTROSPECT_CLIENT_SECRET}
          introspection-uri: ${OAUTH2_ENDPOINT_PREFIX}/oauth2/introspect

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 200
          time_zone: ${info.app.timezone}
        order_inserts: true
        order_updates: true
        enable_lazy_load_no_trans: true
        session_factory:
          statement_inspector: cloud.xcan.angus.core.jpa.interceptor.TenantInterceptor
    database: '@databaseType@'
    database-platform: '@databaseDialect@'
    open-in-view: false

logging:
  level:
    org: WARN
    com: WARN


